#!/usr/bin/env node
/* Downloads the Inter font (woff2) from the Google Fonts css2 endpoint and writes
 * a self-hosted fonts/inter.css. Run from the repo root:
 *   node tools/fetch-inter.js
 * Idempotent — safe to re-run to update the font files. */
"use strict";

const fs = require("fs");
const path = require("path");

const FONTS_DIR = path.join(__dirname, "..", "fonts");
/* latin + latin-ext (cs) + cyrillic (ru/uk), weights actually used by the UI */
const CSS_URL = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap";
const KEEP_SUBSETS = new Set(["latin", "latin-ext", "cyrillic", "cyrillic-ext"]);

async function main() {
  fs.mkdirSync(FONTS_DIR, { recursive: true });

  /* this UA makes the endpoint return woff2 URLs instead of ttf */
  const css = await fetch(CSS_URL, {
    headers: {
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
    }
  }).then(function (r) {
    if (!r.ok) throw new Error("css2 fetch failed: " + r.status);
    return r.text();
  });

  /* css2 blocks look like: (subset comment) @font-face { font-family: 'Inter'; ... src: url(...) format('woff2'); unicode-range: ...; } */
  const blocks = css.split("@font-face").slice(1);
  let out = "/* Self-hosted Inter — generated by tools/fetch-inter.js. Do not edit by hand. */\n";
  const downloads = [];

  blocks.forEach(function (block) {
    const head = block.match(/\/\*\s*([a-z-]+)\s*\*\//);
    const family = block.match(/font-family:\s*'([^']+)'/);
    const weight = block.match(/font-weight:\s*(\d+)/);
    const src = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    const range = block.match(/unicode-range:\s*([^;]+);/);
    if (!head || !family || !weight || !src) return;

    const subset = head[1];
    if (!KEEP_SUBSETS.has(subset)) return;

    const fileName = "inter-" + subset + "-" + weight[1] + ".woff2";
    downloads.push({ url: src[1], fileName: fileName });

    out += "/* " + subset + " */\n@font-face{\n" +
      "  font-family:'Inter';\n" +
      "  font-style:normal;\n" +
      "  font-weight:" + weight[1] + ";\n" +
      "  font-display:swap;\n" +
      "  src:url('./" + fileName + "') format('woff2');\n" +
      (range ? "  unicode-range:" + range[1].trim() + ";\n" : "") +
      "}\n";
  });

  if (!downloads.length) throw new Error("no font blocks parsed — Google changed the css2 format?");

  for (const d of downloads) {
    const buf = await fetch(d.url).then(function (r) {
      if (!r.ok) throw new Error("font fetch failed: " + r.status + " " + d.url);
      return r.arrayBuffer();
    });
    fs.writeFileSync(path.join(FONTS_DIR, d.fileName), Buffer.from(buf));
  }

  fs.writeFileSync(path.join(FONTS_DIR, "inter.css"), out);
  console.log("ok: " + downloads.length + " font files + fonts/inter.css written");
}

main().catch(function (err) {
  console.error("fetch-inter failed:", err.message);
  process.exit(1);
});
